version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAAWSDev1706TestProject
  gitServerName: Kusi_VCTest
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
